# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_user_signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import requests
import os
from time import sleep
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from PyQt5.QtCore import QTimer


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(917, 461)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 901, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 901, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(360, 380, 211, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.signup)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(190, 320, 551, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(190, 150, 551, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(160, 120, 611, 241))
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_8.setLineWidth(5)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.label_6.raise_()
        self.gridLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "NEXUS"))
        self.label_2.setText(_translate("Form", "VIT PUNE PERSONNEL SIGN-UP PANEL"))
        self.pushButton.setText(_translate("Form", "SIGN-UP"))
        self.label_6.setText(_translate("Form", "Note: Sign-up to gain access to the VIT Network"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_4.setText(_translate("Form", "Email ID"))
        self.label_5.setText(_translate("Form", "Registration Number"))
        self.label_7.setText(_translate("Form", "Role"))
        self.comboBox.setItemText(0, _translate("Form", "- Choose -"))
        self.comboBox.setItemText(1, _translate("Form", "(Admin) Head of Department"))
        self.comboBox.setItemText(2, _translate("Form", "Teacher"))

    def signup(self):
        name = self.lineEdit.text()
        email = self.lineEdit_2.text()
        username = self.lineEdit_3.text()
        type_login = self.comboBox.currentText()
        # print(name, email, username, type_login)

        if self.comboBox.currentText() == '(Admin) Head of Department':
            type_login = 'A'
        
        elif self.comboBox.currentText() == 'Teacher':
            type_login = 'T'

        else:
            print("Not accepted!")

        url = 'https://nexus-api-vit.herokuapp.com/cred_verify/'

        # set the data to be sent to the API
        data = {
            "name": name,
            "email": email,
            "username": username,
            "password": username,
            "type_login": type_login
        }

        # convert the data to JSON format
        json_data = json.dumps(data)

        # set the headers for the request
        headers = {
            'Content-Type': 'application/json'
        }

        # send the request to the API endpoint
        response = requests.post(url, data=json_data, headers=headers)

        # check the response status code
        if response.status_code == 201:
            # data was successfully pushed to the API
            self.label_6.setText('You have been added into the system. You can now proceed logging in.')
            sleep(3.5)

            smtp_server = "smtp.gmail.com"
            smtp_port = 587
            smtp_username = "aniruddha.kulkarni191@vit.edu"
            smtp_password = "Aniruddha@1234"

            # Set up the email message
            message = MIMEMultipart()
            message["From"] = "aniruddha.kulkarni191@vit.edu"
            message["To"] = str(email)
            message["Cc"] = "aniruddha.k1911@gmail.com"
            message["Subject"] = "User Registered"

            body = f"Greetings from Nexus,\n\nYou have successfully registered into the system. Please find your details below:\n\nName: {name}\nEmail: {email}\nUsername: {username}\nGenerated Password: {username}\nRole: {type_login}\n\nRegards,\nTeam Nexus."
            message.attach(MIMEText(body, "plain"))

            # Connect to the SMTP server and send the email
            with smtplib.SMTP(smtp_server, smtp_port) as server:
                server.starttls()
                server.login(smtp_username, smtp_password)
                recipients = [message["To"]] + message["Cc"].split(",")
                server.sendmail(message["From"],
                                recipients, message.as_string())

            # print("Email sent successfully.")
            os.system('python gui_login.py')
            QtCore.QTimer.singleShot(25, QtWidgets.qApp.quit)
        else:
            self.label_6.setText('Sign-up Failed. Please try again.')
            self.lineEdit.setText('')
            self.lineEdit_2.setText('')
            self.lineEdit_3.setText('')
            self.comboBox.setCurrentText('- Choose -')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
